import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Head from 'next/head';
import { Grid } from '@mui/material';

const theme = createTheme({
    typography: {
        fontFamily: "Satoshi"
      }
});

function Layout({children}){

    return(
    <Grid sx={{backgroundColor: "#0F876E", wrap: "wrap", width: '100%', height: "100vh"}}>
        <Head>
        <title>Leaf Desafio React</title>
        <meta name="description" content="Generated by created next app" />
        <link rel="icon" href="/leaf.jpg"/> 
        <link
            rel="preload"
            href="/fonts/Satoshi/Satoshi-Regular.ttf"
            as="font"
            crossOrigin=""
          />
             
        </Head>
        <ThemeProvider theme={theme}>
            {children}
        </ThemeProvider>
    </Grid>
    )
}

export default Layout;